[build]
  publish = "dist/"
  command = "npx eleventy && gulp"

[[redirects]]
  from = "/perfmatters"
  to = "https://slides.com/tatianamac/how-privilege-defines-performance/fullscreen"

[[redirects]]
  from = "/edgecases"
  to = "https://slides.com/tatianamac/edge-cases/fullscreen"

[[redirects]]
  from = "/sunday.html"
  to = "/posts/sunday.html"
  
  [[redirects]]
  from = "/cracked.html"
  to = "/posts/cracked.html"

[[redirects]]
  from = "/monday-communication-tips.html"
  to = "/posts/monday-communication-tips.html"

[[redirects]]
 from = "/tired.html"
  to = "/posts/tired.html"